# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV[“alanseigerman@gmail.com”]  %>
  email_provider_password: <%= ENV[“google7173”] %>
  mailchimp_api_key: %<=ENV[“91db9769dba7215fbc2193e9af52203b-us9”] %>
  mailchimp_list_id: %<[“82826b516de”] %>
  domain_name: example.com
  owner_email: <%= ENV[“alanseigerman@gmail.com”] %>
  secret_key_base:980d2ce4fe0ecfbc5c90f6f361f8ff5a88fdd77f584469a8abe1bc771c4881420d7e72dbc818d0b6916302b72861500fc9710ed5c1ab3474f32c4e320d950329

test:
  secret_key_base: 23c3ab3dff6c76c4ab230798b5ce6f0c18d85147e065d8b5e1c3eb91be9699020f70952274305af1eddca3a062b6f18c80699777b3b47c6cf665b774ff571593

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
email_provider_username: <%= ENV[“alanseigerman@gmail.com”]  %>
  email_provider_password: <%= ENV[“google7173”] %>
  mailchimp_api_key: %<=ENV[“91db9769dba7215fbc2193e9af52203b-us9”] %>
  mailchimp_list_id: %<[“82826b516de”] %>
  domain_name: example.com
  owner_email: <%= ENV[“alanseigerman@gmail.com”] %>  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
